name: Deploy updates on push

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy the demo
    runs-on: ubuntu-latest
    # Note: almost all of the steps where copied over from
    #  https://github.com/illright/attractions/blob/main/.github/workflows/
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node 14 📦
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm 🧰
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.2

      - name: Build demo 🔧
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
